### PR TITLE
create-hello-microverse

### PR DESCRIPTION
**Pull request by Estherstarr**
Microverse first project.

### CODE REVIEW

**Review by gemmen29 — CHANGES_REQUESTED** [review]
Hi @Estherstarr, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- Kindly add [.hintrc](https://github.com/microverseinc/linters-config/blob/master/html-css/.hintrc) file in linters repo.
_Check the comments under the review._



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [Optional] Please give the branch a meaningful name instead of `feature1`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Estherstarr** [comment]
I've made a mistake, I changed the name of the branch from feature1 to
create-hello-microverse and deleted the previous one.

**Comment by Estherstarr** [comment]
Please can you advise me on the necessary step to reverse my mistake.

**Comment by prolajumokeoni** [comment]
Hello @Estherstarr, when submitting for a re-review kindly use the same pull request 👍🏿

**Pull request closed without merging**
